on: push
name: npm build, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10', '8' ]
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test    
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t richardbrash/brash-code-challenge-api .
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push richardbrash/brash-code-challenge-api
